version: '3.8'
services:
  app:
    image: php-fpm:latest
    container_name: app-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./public_html:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - apps
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "80:8000"
    volumes:
      - ./public_html:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - apps
    depends_on:
      - app
      - db
    
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - apps
networks:
  apps:
    driver: bridge
volumes:
  dbdata:
    driver: local
